[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "salesforce"
version = "@toml.version@"
export = ["salesforce", "salesforce.bulk", "salesforce.soap"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-salesforce"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/salesforce-native-@project.version@.jar"
groupId = "io.ballerinax"
artifactId = "salesforce"
version = "@project.version@"
